import { PhotoProps } from "@/types";

const artArray: PhotoProps[] = [
	{
		imageSrc: ["/toys3.jpg"],
		imageAlt: "Drawing",
		materials: "Acrylic Paint, Pen, Watercolor",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/toys6.jpg"],
		imageAlt: "Drawing",
		materials: "Photo collage",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/toys1.jpg"],
		imageAlt: "Drawing",
		materials: "Colored Penvils",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/toys2.jpg"],
		imageAlt: "Drawing",
		materials: "Acrylic Paint, Oil Paint",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/toys5.jpg"],
		imageAlt: "Drawing",
		materials: "Colored Penvils",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/misc3.jpg"],
		imageAlt: "Drawing",
		materials: "Charcoal",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/doodle1.jpg"],
		imageAlt: "Drawing",
		materials: "Pen",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/doodle2.jpg"],
		imageAlt: "Drawing",
		materials: "Pen",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/toys4.jpg"],
		imageAlt: "Drawing",
		materials: "Acrylic Paint, Colored Penvils, Pen, Watercolor",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/misc2.jpg"],
		imageAlt: "Drawing",
		materials: "Acrylic Paint, Markers",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/misc1.jpg"],
		imageAlt: "Drawing",
		materials: "Acrylic Paint, Oil Paint, Pen, Watercolor",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/misc4.jpg"],
		imageAlt: "Drawing",
		materials: "Acrylic Paint, Watercolor",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
];

export default artArray;
