import { PhotoProps } from "@/types";

const ceramicsArray: PhotoProps[] = [
	{
		imageSrc: ["/ceramics/mug1.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/ceramics/vase1.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/ceramics/vase2.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/ceramics/vase3.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	// {
	// 	imageSrc: ["/ceramics/bunny1.jpg"],
	// 	imageAlt: "Ceramic",
	// 	materials: "",
	// 	collection: "",
	// 	stats: "",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: [],
	// 	index: 0,
	// },
	{
		imageSrc: ["/ceramics/bunny2.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/ceramics/bunny3.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/ceramics/bunny4.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	{
		imageSrc: ["/ceramics/bunnyKinda.jpg"],
		imageAlt: "Ceramic",
		materials: "",
		collection: "",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [],
		index: 0,
	},
	// {
	// 	imageSrc: ["/ceramics/pikmin.jpg"],
	// 	imageAlt: "Ceramic",
	// 	materials: "",
	// 	collection: "",
	// 	stats: "",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: [],
	// 	index: 0,
	// },
	// {
	// 	imageSrc: ["/ceramics/pikmin2.jpg"],
	// 	imageAlt: "Ceramic",
	// 	materials: "",
	// 	collection: "",
	// 	stats: "",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: [],
	// 	index: 0,
	// },
];

export default ceramicsArray;
